### PR TITLE
build: add build patch

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/Homebrew/homebrew-core/pull/120508

### CODE REVIEW

**Comment by yuriichalov** [comment]
Thanks for your submission! Snort3 team will take a look and test your changes.

**Comment by chenrui333** [comment]
np, @yuriichalov let me know if this patch works for you folks, I have adopted in the homebrew side. Thanks!

**Comment by yuriichalov** [comment]
@chenrui333 Thank you for your submission! The Snort3 team decided to add these changes to the product.

**Comment by chenrui333** [comment]
> @chenrui333 Thank you for your submission! The Snort3 team decided to add these changes.

Thanks! @yuriichalov, where can I see the changes?

**Comment by chenrui333** [comment]
> > where can I see the changes?
> 
> Any changes proposed will have to pass an internal development process (which includes more testing, review, etc.). Only after that the changes could be published.

I see, can you also submit the rest of the patch as well? (relates to https://github.com/Homebrew/homebrew-core/pull/121005)

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/121608

**Comment by chenrui333** [comment]
FYI, we are still using this patch for homebrew-core build, https://github.com/Homebrew/homebrew-core/pull/123025

**Comment by InverseRE** [comment]
@chenrui333 
This will be addressed in the next release by removing 'malloc.h' from memory_cap.cc file.
As for another file, do you really have HAVE_MALLOC_TRIM enabled in your build?

**Comment by chenrui333** [comment]
I think it works fine now, closing this PR

relates to https://github.com/Homebrew/homebrew-core/pull/130354

**Pull request closed without merging**
