### PR TITLE
Alpine Linux Support - Unsigned macro replace

### PR DESCRIPTION
**Pull request by satchm0h**
This is the first pull request of a series to integrate changes I have made to get Snort3 to build on Alpine Linux leveraging the [musl libc](https://www.musl-libc.org/) implementation. The end goal is to create a thin containerized version Snort3 that will build from the GitHub source. 

To validate the changes, I have applied them to my fork the GitHub master and built w/ unit tests and run `snort --catch-test all`. Both without any errors.

This PR removes the use of the `u_char` and `u_short` macros. I have replaced them with `uint8_t` and `unsigned short` respectively.

### CODE REVIEW

**Comment by snortadmin** [comment]
Ted, the Aug 16th commit (8220a36) shows master being pulled into unsigned_macro_replace.  Although I hear it can be done that way, this is backwards from how we work.  Please rebase your commits on the tip of master so we can kick it through our CI process.

Thanks
Russ

**Comment by satchm0h** [comment]
FYI, this is the documented Github workflow for PRs.

https://help.github.com/articles/syncing-a-fork/

Happy to do it differently.

**Comment by snortadmin** [comment]
Right, but that shows merging upstream/master into your local master, not into your feature branch.

git checkout master
git pull origin master
git checkout unsigned_macro_replace
git reset 8220a36
git add <files>
git commit -m 'build: remove obsolete u_char and u_short'
git add <files>
git commit -m 'style: align some comments'

That will fix it as of now.  If more commits go to master, you may need to do:

git rebase -i master

afterwards.

Note the commit messages are just demonstrating our style (module: what), not to be taken literally.

**Comment by satchm0h** [comment]
Sure enough...that is totally the wrong link. I swear I found a github page that asserted I should do the merge from master, but now they all seem to align with your assertion that `git rebase` is what I was actually looking for. Live and learn :)

I'll close this one. Go understand `git reset` and `git rebase -i`, and submit a new one.

**Pull request closed without merging**
